# Generated by Django 5.2.5 on 2025-08-25 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bam', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=63, unique=True)),
                ('descripcion_evento', models.TextField()),
                ('id_cuestionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuentro_v1.cuestionario')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('puntaje', models.IntegerField(blank=True)),
                ('es_moderador', models.BooleanField(default=False)),
                ('bam_usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='encuentro_v1.bam')),
                ('evento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='encuentro_v1.evento')),
                ('user_perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bam',
            name='lider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuentro_v1.perfil'),
        ),
    ]
